-- GENERATED by `npm run gyms:sql` from src/data/gyms.ts. Do not edit by hand.
-- Run in the Supabase SQL Editor whenever the built-in gym list changes.

insert into public.gyms (id, name, sort_order) values
  ('0859db82-c520-4f55-8b0a-0e7362d8f2fe', 'Sample Boulder Gym (placeholder)', 1),
  ('aad09cb6-fb53-401f-879a-caa3db961169', 'Sample Climbing Gym (placeholder)', 2)
on conflict (id) do update
  set name = excluded.name, sort_order = excluded.sort_order, is_active = true, updated_at = now();

-- Gyms that are no longer in the list are hidden, not deleted: passes may still point at them.
update public.gyms set is_active = false, updated_at = now() where id not in ('0859db82-c520-4f55-8b0a-0e7362d8f2fe', 'aad09cb6-fb53-401f-879a-caa3db961169');
