import type { BuiltinGym } from '../domain/gyms'

const quote = (text: string) => `'${text.replaceAll("'", "''")}'`

/**
 * The SQL that loads the built-in gym names into the account database (`public.gyms`): the same
 * names with the same fixed ids as the bundled list, so a pass made offline points at the right
 * gym once it syncs. Safe to run again whenever the list changes: names are updated, and a gym
 * that left the list is hidden (`is_active = false`), never deleted, because passes may still use it.
 *
 * `supabase/seed_gyms.sql` is this output. Regenerate it with `npm run gyms:sql`; a test fails if
 * the two drift apart.
 */
export function gymSeedSql(gyms: BuiltinGym[]): string {
  const rows = gyms.map((g, i) => `  (${quote(g.id)}, ${quote(g.name)}, ${i + 1})`).join(',\n')
  const ids = gyms.map((g) => quote(g.id)).join(', ')
  return [
    '-- GENERATED by `npm run gyms:sql` from src/data/gyms.ts. Do not edit by hand.',
    '-- Run in the Supabase SQL Editor whenever the built-in gym list changes.',
    '',
    'insert into public.gyms (id, name, sort_order) values',
    rows,
    'on conflict (id) do update',
    '  set name = excluded.name, sort_order = excluded.sort_order, is_active = true, updated_at = now();',
    '',
    '-- Gyms that are no longer in the list are hidden, not deleted: passes may still point at them.',
    gyms.length === 0
      ? 'update public.gyms set is_active = false, updated_at = now();'
      : `update public.gyms set is_active = false, updated_at = now() where id not in (${ids});`,
    '',
  ].join('\n')
}
